-- Sample data for products table
INSERT INTO public.products (
  name, description, price, category, subcategory, brand, image_url, 
  sizes, colors, stock_quantity, is_sale, sale_price, rating, review_count, tags
) VALUES
-- Women's Products
(
  'Elegant Evening Dress',
  'A stunning black evening dress perfect for special occasions. Made from premium silk with intricate lace details.',
  299.99,
  'women',
  'dresses',
  'Luxe Fashion',
  '/api/placeholder/400/600',
  ARRAY['XS', 'S', 'M', 'L', 'XL'],
  ARRAY['Black', 'Navy', 'Burgundy'],
  15,
  true,
  199.99,
  4.8,
  24,
  ARRAY['evening', 'formal', 'silk', 'elegant', 'special occasion']
),
(
  'Casual Summer Blouse',
  'Light and breezy cotton blouse perfect for summer days. Features a relaxed fit and beautiful floral print.',
  79.99,
  'women',
  'tops',
  'Summer Breeze',
  '/api/placeholder/400/600',
  ARRAY['XS', 'S', 'M', 'L', 'XL'],
  ARRAY['White', 'Pink', 'Blue', 'Yellow'],
  25,
  false,
  NULL,
  4.5,
  18,
  ARRAY['casual', 'summer', 'cotton', 'floral', 'comfortable']
),
(
  'Designer Skinny Jeans',
  'Premium denim skinny jeans with stretch comfort. Classic design that pairs with any top.',
  129.99,
  'women',
  'bottoms',
  'Denim Co.',
  '/api/placeholder/400/600',
  ARRAY['24', '25', '26', '27', '28', '29', '30', '32'],
  ARRAY['Dark Blue', 'Light Blue', 'Black'],
  30,
  false,
  NULL,
  4.6,
  42,
  ARRAY['denim', 'skinny', 'stretch', 'classic', 'versatile']
),

-- Men's Products
(
  'Classic Business Suit',
  'Tailored business suit made from premium wool. Perfect for professional settings and formal events.',
  499.99,
  'men',
  'suits',
  'Executive Style',
  '/api/placeholder/400/600',
  ARRAY['S', 'M', 'L', 'XL', 'XXL'],
  ARRAY['Navy', 'Charcoal', 'Black'],
  12,
  true,
  399.99,
  4.9,
  31,
  ARRAY['business', 'formal', 'wool', 'tailored', 'professional']
),
(
  'Casual Cotton Polo',
  'Comfortable cotton polo shirt perfect for casual outings and weekend activities.',
  59.99,
  'men',
  'tops',
  'Casual Kings',
  '/api/placeholder/400/600',
  ARRAY['S', 'M', 'L', 'XL', 'XXL'],
  ARRAY['White', 'Navy', 'Red', 'Green', 'Gray'],
  40,
  false,
  NULL,
  4.3,
  27,
  ARRAY['casual', 'cotton', 'polo', 'comfortable', 'weekend']
),
(
  'Premium Chinos',
  'Slim-fit chinos made from high-quality cotton twill. Versatile pants for both casual and smart-casual looks.',
  89.99,
  'men',
  'bottoms',
  'Urban Fit',
  '/api/placeholder/400/600',
  ARRAY['28', '30', '32', '34', '36', '38'],
  ARRAY['Khaki', 'Navy', 'Black', 'Gray'],
  35,
  false,
  NULL,
  4.4,
  19,
  ARRAY['chinos', 'slim-fit', 'versatile', 'cotton', 'smart-casual']
),

-- Accessories
(
  'Leather Handbag',
  'Genuine leather handbag with multiple compartments. Perfect for work or everyday use.',
  199.99,
  'accessories',
  'bags',
  'Leather Craft',
  '/api/placeholder/400/600',
  ARRAY['One Size'],
  ARRAY['Black', 'Brown', 'Tan'],
  20,
  false,
  NULL,
  4.7,
  33,
  ARRAY['leather', 'handbag', 'work', 'everyday', 'genuine leather']
),
(
  'Luxury Watch',
  'Stainless steel watch with automatic movement. A timeless piece for any outfit.',
  349.99,
  'accessories',
  'watches',
  'Time Masters',
  '/api/placeholder/400/600',
  ARRAY['One Size'],
  ARRAY['Silver', 'Gold', 'Black'],
  8,
  true,
  279.99,
  4.9,
  15,
  ARRAY['luxury', 'watch', 'stainless steel', 'automatic', 'timeless']
),
(
  'Designer Sunglasses',
  'UV protection sunglasses with polarized lenses. Stylish and functional.',
  149.99,
  'accessories',
  'eyewear',
  'Sun Shield',
  '/api/placeholder/400/600',
  ARRAY['One Size'],
  ARRAY['Black', 'Tortoise', 'Silver'],
  25,
  false,
  NULL,
  4.2,
  21,
  ARRAY['sunglasses', 'UV protection', 'polarized', 'designer', 'stylish']
),
(
  'Wool Winter Scarf',
  'Soft wool scarf perfect for cold weather. Available in various colors and patterns.',
  39.99,
  'accessories',
  'scarves',
  'Winter Warmth',
  '/api/placeholder/400/600',
  ARRAY['One Size'],
  ARRAY['Red', 'Blue', 'Gray', 'Beige'],
  50,
  true,
  29.99,
  4.1,
  12,
  ARRAY['wool', 'winter', 'scarf', 'warm', 'soft']
);
