// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pyzlsolhskzisrxzwqpp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB5emxzb2xoc2t6aXNyeHp3cXBwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1NzczOTksImV4cCI6MjA3MDE1MzM5OX0.uu7sTKpyL86VkAzE7lghQ2C0I-yLS87Cc7kK4tV3UnM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});